### ISSUE TITLE
Include libuuid.so.1 in canvas prebuilt

### ISSUE THREAD

**Issue by jwerre** [Automattic/node-canvas#1448]
## Issue or Feature
After compiling node-canvas a Amazon Linux and deploying to Lambda I'm getting the following error:

        Error: libuuid.so.1: cannot open shared object file: No such file or directory
            at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
            at Module.load (internal/modules/cjs/loader.js:600:32)
            at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
            at Function.Module._load (internal/modules/cjs/loader.js:531:3)
            at Module.require (internal/modules/cjs/loader.js:637:17)
            at require (internal/modules/cjs/helpers.js:22:18)
            at Object.<anonymous> (/var/task/node_modules/canvas/lib/bindings.js:3:18)
            at Module._compile (internal/modules/cjs/loader.js:701:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
            at Module.load (internal/modules/cjs/loader.js:600:32)

I believe this has something to do with `libuuid.so.1` no longer being included in the Lambda runtime. Would it be possible to get this included in the prebuild?

#### 1. Spin up an Amazon Linux 2 AMI: 

I installed this one. [amzn2-ami-hvm-2.0.20190313-x86_64-gp2](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;search=amzn2-ami-hvm-2.0.20190313-x86_64-gp2;sort=tag:Name). Then connect to the server over ssh.

#### 2. Install node 10

```zsh
curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -
sudo yum install -y nodejs
```

#### 3. Install Serverless

```zsh
sudo npm install --global serverless
```

#### 4. Create project directory and install Canvas

```zsh
mkdir test && cd test
npm install canvas@2.5.0 --save
```

#### 5. Create Lambda handler `index.js`

```js
let {createCanvas} = require("canvas");

function hello(event, context, callback) {
	let
		canvas = createCanvas(200, 200),
		ctx = canvas.getContext('2d');

	// Write "Awesome!"
	ctx.font = '30px Impact';
	ctx.rotate(0.1);
	ctx.fillText('Awesome!', 50, 100);

	// Draw line under text
	let text = ctx.measureText('Awesome!');
	ctx.strokeStyle = 'rgba(0,0,0,0.5)';
	ctx.beginPath();
	ctx.lineTo(50, 102);
	ctx.lineTo(50 + text.width, 102);
	ctx.stroke();

	callback(null, '<img src="' + canvas.toDataURL() + '" />');
}

module.exports = {hello};
```

#### 6. Create `serverless.yml`

```yaml
service: canvas-test

provider:
  name: aws
  runtime: nodejs10.x
  stage: development
  region: us-east-1
  memorySize: 128
  timeout: 10

functions:
  hello:
    handler: index.hello

```

#### 7. Deploy the function

```zsh
serverless deploy
```

#### 8. Invoke the function

```zsh
serverless invoke --function hello
```

## Environment
* canvas@2.5.0 
* node@10.16.0

**Comment by jwerre** [comment]
I also tried deploying from Docker and it produced the same error. Here's the Docker file I used:

```dockerfile
FROM amazonlinux:latest

RUN yum remove -y nodejs nodesource-release
RUN curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
RUN yum install -y nodejs zip

RUN mkdir /test
COPY ./package.json /test/
COPY ./package-lock.json /test/

WORKDIR /test

ENTRYPOINT ["npm"]
CMD ["install"]
```

**Comment by jwerre** [comment]
I create a Lambda layer which addresses this issue:

https://github.com/jwerre/node-canvas-lambda

**Comment by chpio** [comment]
Any changes on this one? Do i need to vendor the lib by my self and copy it into `node_modules/canvas`?

**Comment by jwerre** [comment]
@chpio, you need to use the [Lambda Layer](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html) here: https://github.com/jwerre/node-canvas-lambda

**Comment by chpio** [comment]
@jwerre im not using aws

**Comment by nirmalpatel59** [comment]
I am getting the same error while using **jsdom** with node 12 in AWS Lambda serverless.
will creating a layer for **_canvas-lib64-layer.zip_** will be enough to resolve the issue?

**Comment by jwerre** [comment]
@nirmalpatel59 this layer should solve the issue but I haven't tired it. Doesn't hurt to try though... it's super easy. Just follow the installation instructions.

**Comment by nirmalpatel59** [comment]
> @nirmalpatel59 this layer should solve the issue but I haven't tried it. Doesn't hurt to try though... it's super easy. Just follow the installation instructions.

Yes, Adding this layer has solved the issue.

**Comment by JoeHart** [comment]
Hey I'm also getting this issue in a Vercel lambda. I'm unclear if there's a way of doing a similar `layer` fix for them. This comment is essentially a +1 for including `libuuid.so.1` into the prebuilt.

**Comment by JollyGrin** [comment]
I'm additionally receiving this error in vercel @JoeHart

**Comment by joe-bell** [comment]
For **Vercel** users, try [@shawninder's solution](https://github.com/vercel/vercel/issues/3460#issuecomment-583072848).

Create a `vercel-build` key in your `package.json` and run the following:

```json
"scripts": {
  "build": "next build",
  "vercel-build": "yum install libuuid-devel libmount-devel && cp /lib64/{libuuid,libmount,libblkid}.so.1 node_modules/canvas/build/Release/ && npm run build",
}
```

Not the prettiest solution but it works a treat 🚀 

--

cc @JoeHart @JollyGrin

**Comment by Feofast** [comment]
i put this in now.json file
`"scripts": {
  "build": "next build",
  "vercel-build": "yum install libuuid-devel libmount-devel && cp /lib64/{libuuid,libmount,libblkid}.so.1 node_modules/canvas/build/Release/ && npm run build",
}`

**Comment by Shvembldr** [comment]
> For **Vercel** users, try [@shawninder's solution](https://github.com/vercel/vercel/issues/3460#issuecomment-583072848).
> 
> Create a `vercel-build` key in your `package.json` and run the following:
> 
> ```json
> "scripts": {
>   "build": "next build",
>   "vercel-build": "yum install libuuid-devel libmount-devel && cp /lib64/{libuuid,libmount,libblkid}.so.1 node_modules/canvas/build/Release/ && npm run build",
> }
> ```
> 
> Not the prettiest solution but it works a treat 🚀
> 
> cc @JoeHart @JollyGrin

Doesn't work for me. As a result, I have:

ERROR	Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /var/task/node_modules/canvas/build/Release/libpng16.so.16)

I haven't found anywhere how to deal with ZLIB_1.2.9
Any thoughts?

**Comment by spidgorny** [comment]
I'm also using Vercel. I also have ZLIB error ```ERROR	Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /var/task/node_modules/canvas/build/Release/libpng16.so.16)```. My fix was to compile zlib from source.
```
wget https://zlib.net/fossils/zlib-1.2.9.tar.gz
tar -xf zlib-1.2.9.tar.gz
cd zlib-1.2.9
sh configure
make
ls -l libz*
cp libz.so.1 ../node_modules/canvas/build/Release/
cp libz.so.1 /lib64/libz.so
cp libz.so.1 /lib64/libz.so.1
cp libz.so.1 /lib64/libz.so.1.2.9
cp libz.so.1 /lib64/
rm /lib64/libz.so
rm /lib64/libz.so.1
ln -s /lib64/libz.so.1.2.9 /lib64/libz.so
ln -s /lib64/libz.so.1.2.9 /lib64/libz.so.1
ls -l /lib64/libz*
ls -l /lib64/libpng*
cd ..
```

This has fixed ZLIB issue. But I get ```ERROR	Error: libpng16.so.16: cannot open shared object file: No such file or directory```
Fixed by downloading libpng.

```
wget http://slackware.osuosl.org/slackware64-current/slackware64/l/libpng-1.6.37-x86_64-3.txz
tar -xf libpng-1.6.37-x86_64-3.txz
ls -l usr/lib64
cp usr/lib64/libpng16.so.16.37.0 /lib64/libpng16.so.16
```

Finally I get
```Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /lib64/libpng16.so.16)```

Something's seriously wrong. Either with Vercel docker image or node-canvas bundled libs.
Any ideas?

**Comment by Shvembldr** [comment]
I successfully deployed it on heroku
problem is in Vercel docker image

**Comment by elmariachi111** [comment]
[switched to node 12](https://vercel.com/docs/runtimes#official-runtimes/node-js/node-js-version) runtime and it just started working \o/ Still have the weird yum install hack in my package.json, though, looks like:

```
  "scripts": {
    "vercel-build": "yum install libuuid-devel libmount-devel zlib && cp /lib64/{libuuid,libmount,libblkid,libz}.so.1 node_modules/canvas/build/Release/"
  }
  ```

**Comment by Mic75** [comment]
Got it working by downgrading to node 12 runtime (not using the `yum install hack`)

**Comment by aagiulian** [comment]
Getting node-canvas to work on an aws lambda is really a struggle so far, first time using lambda tho.
After failing to work with my node_modules (elf header error) I recompiled all the node_modules on an amazon linux virtual machine, gave me the libuid error.
Now trying to add node-canvas as a layer with this jwerre's package, and I get the ```"/lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /var/task/node_modules/canvas/build/Release/libpng16.so.16)"``` error.
Any tip to fix this ?

**Comment by tk1024** [comment]
> "/lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /var/task/node_modules/canvas/build/Release/libpng16.so.16)"

I was in trouble with the same error. And I downgraded from v2.7.0 to v2.6.1 and it worked.

**Comment by feuxfollets1013** [comment]
I got the same error while using `jsdom` with [`@aws-cdk/aws-lambda-nodejs`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html).

I tried to add `jsdom` to esbuild external modules option(bundling.nodeModules), and then it worked.

```
import { Rule, Schedule } from '@aws-cdk/aws-events';
import { LambdaFunction } from '@aws-cdk/aws-events-targets';
import { Runtime } from '@aws-cdk/aws-lambda';
import { NodejsFunction } from '@aws-cdk/aws-lambda-nodejs';
import * as cdk from '@aws-cdk/core';

export class MyStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const lambda = new NodejsFunction(this, 'handler', {
      runtime: Runtime.NODEJS_14_X,
      timeout: cdk.Duration.seconds(10),
      memorySize: 256,
      environment: {
        DATABASE_URL: process.env.DATABASE_URL || '',
      },
      bundling: {
        forceDockerBundling: true,
        nodeModules: ['@prisma/client', 'prisma', 'jsdom'], // external modules
        commandHooks: {
          beforeBundling() {
            return [];
          },
          beforeInstall(inputDir: string, outputDir: string) {
            return [`cp -R ${inputDir}/prisma ${outputDir}/`];
          },
          afterBundling(_, outputDir: string) {
            return [
              `cd ${outputDir}`,
              `yarn prisma generate`,
              `rm -rf node_modules/@prisma/engines`,
              `rm -rf node_modules/@prisma/client/node_modules node_modules/.bin node_modules/prisma`,
            ];
          },
        },
      },
    });
   ...
```

**Comment by maxieduncan** [comment]
I wasn't able to use the lambda layer provided but did manage to use the same approach using [Lambda Container Image Support](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/) and a simple Dockerfile:

```FROM public.ecr.aws/lambda/nodejs:14

# set up container
RUN yum -y update \
&& yum -y groupinstall "Development Tools" \
&& yum install -y nodejs gcc-c++ cairo-devel libjpeg-turbo-devel pango-devel giflib-devel

RUN npm install --build-from-source canvas@next
RUN npm install \
chartjs-node-canvas \
chart.js

COPY src/ package* ./
RUN npm install```

**Comment by advanw** [comment]
Did you manage to fix this issue @chpio ? I'm using Google Cloud Run and it's also giving the error " Error: libuuid.so.1: cannot open shared object file: No such file or directory". The package libuuid1 is already installed.

**Comment by BasToTheMax** [comment]
Hi!
I have this issue. Has a fix been found? (I am using replit)

**Comment by jwerre** [comment]
@BasToTheMax https://github.com/jwerre/node-canvas-lambda
